// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shenara.Api.Data;

#nullable disable

namespace Shenara.Api.Migrations
{
    [DbContext(typeof(ShenaraDbContext))]
    [Migration("20260501190806_SeedTimestampStability")]
    partial class SeedTimestampStability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shenara.Api.Models.BookingInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("EventDate");

                    b.HasIndex("RemoteAddress");

                    b.HasIndex("Status");

                    b.ToTable("BookingInquiries");
                });

            modelBuilder.Entity("Shenara.Api.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventType = "Birthday",
                            ImageUrl = "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=80",
                            IsFeatured = true,
                            Title = "Blush birthday backdrop"
                        },
                        new
                        {
                            Id = 2,
                            EventType = "Reception",
                            ImageUrl = "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=80",
                            IsFeatured = true,
                            Title = "Elegant reception detail"
                        },
                        new
                        {
                            Id = 3,
                            EventType = "Shower",
                            ImageUrl = "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=80",
                            IsFeatured = true,
                            Title = "Soft fabric celebration setup"
                        });
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("InventoryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Balloon garlands, clusters, and color palettes.",
                            Name = "Balloons"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Arch frames and feature backdrops.",
                            Name = "Back Arches"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soft fabric backdrops for layered event scenes.",
                            Name = "Drop Cloths"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Accent pieces, stands, and themed decor.",
                            Name = "Props"
                        });
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryImages");
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("InventoryCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumStockAlert")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RentalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCategoryId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("Status");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 10,
                            Color = "Blush",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(2752), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Soft blush, pearl, and champagne balloon mix for elegant celebrations.",
                            InventoryCategoryId = 1,
                            IsFeatured = true,
                            MinimumStockAlert = 3,
                            Name = "Blush Balloon Garland Kit",
                            PrimaryImageUrl = "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=80",
                            RentalPrice = 85m,
                            Size = "Large",
                            Status = 0,
                            StorageLocation = "Shelf A1",
                            TotalQuantity = 12,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(2756), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 2,
                            Color = "Gold",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(8131), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Modern round gold arch for birthdays, showers, engagements, and photo moments.",
                            InventoryCategoryId = 2,
                            IsFeatured = true,
                            MinimumStockAlert = 1,
                            Name = "Round Gold Back Arch",
                            PrimaryImageUrl = "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=900&q=80",
                            RentalPrice = 120m,
                            Size = "7 ft",
                            Status = 0,
                            StorageLocation = "Rack B",
                            TotalQuantity = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(8132), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 8,
                            Color = "Ivory",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(8141), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Layered ivory backdrop fabric for clean, premium event styling.",
                            InventoryCategoryId = 3,
                            IsFeatured = false,
                            MinimumStockAlert = 2,
                            Name = "Ivory Drop Cloth Set",
                            PrimaryImageUrl = "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=900&q=80",
                            RentalPrice = 65m,
                            Size = "10 x 12 ft",
                            Status = 0,
                            StorageLocation = "Bin C2",
                            TotalQuantity = 8,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 19, 8, 5, 119, DateTimeKind.Unspecified).AddTicks(8142), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Shenara.Api.Models.ServiceOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("nvarchar(900)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StartingPrice")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOfferings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Custom garlands, clusters, and installations designed around your event colors and venue.",
                            ImageUrl = "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80",
                            IsFeatured = true,
                            Name = "Balloon Decor",
                            StartingPrice = "From $180"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Statement arches with layered balloons, fabric, florals, signage, and themed details.",
                            ImageUrl = "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80",
                            IsFeatured = true,
                            Name = "Back Arch Styling",
                            StartingPrice = "From $240"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full decor concepts for showers, birthdays, engagements, corporate events, and intimate celebrations.",
                            ImageUrl = "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
                            IsFeatured = true,
                            Name = "Custom Event Setups",
                            StartingPrice = "Custom quote"
                        });
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryImage", b =>
                {
                    b.HasOne("Shenara.Api.Models.InventoryItem", "InventoryItem")
                        .WithMany("Images")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryItem", b =>
                {
                    b.HasOne("Shenara.Api.Models.InventoryCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("InventoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shenara.Api.Models.InventoryItem", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
